# Configuración de Base de Datos (Supabase - esquema logitrack)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-0-ca-central-1.pooler.supabase.com:6543/postgres?sslmode=require&currentSchema=logitrack&prepareThreshold=0}
spring.datasource.username=${DB_USERNAME:postgres.qmzvxsxracwdhewjsekd}
spring.datasource.password=${DB_PASSWORD:Hb39nv9k6f!}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none

# Inicialización de SQL
spring.sql.init.mode=never

# Configuración de Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha

# Configuración de JWT
app.jwt-secret=FirmaSecretaParaLogiTrackProyectoInventarios2026MuySegura
app.jwt-expiration-milliseconds=86400000
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO
logging.level.com.springboot=DEBUG
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN
spring.jpa.properties.hibernate.default_schema=logitrack

