
spring.datasource.url=jdbc:postgresql://pg-38678f10-camiloaav2607-0dc7.a.aivencloud.com:10002/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always
spring.sql.init.defer-datasource-initialization=true
